name: CD

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: "0 5 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout virens
        uses: actions/checkout@v2
        with:
          path: virens

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install requirements
        run: yarn
        working-directory: virens/

      - name: Run Vue build
        run: BASE_API_URL=https://hh3.gbdev.io yarn generate --force
        working-directory: virens/

      - name: Store final build
        uses: actions/upload-pages-artifact@v3
        with:
          path: virens/.output/public

  deploy:
    name: Deploy to GitHub pages
    # Do not run this unless *pushing* to `master`.
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
